apiVersion: v1
kind: Service
metadata:
  name: devboard-frontend-service
  namespace: devboard
spec:
  selector:
    app: devboard-frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080 # host port on which user hit for service discovery
      targetPort: 4173 #pod or application running port
      nodePort: 30080 #port on which cluster is open
